apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-client
  name: udagram-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-client
  template:
    metadata:
      labels:
        app: udagram-client
        service: udagram-client
        api: external        
    spec:
      containers:
      - image: thuchuyen1295/udagram-client
        name: udagram-client
        imagePullPolicy: Always          
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"                
      restartPolicy: Always
